version: "3"
services:
  chat-app-api:
    image: tedthedev/chat-app-api
    container_name: chat-app-api
    build:
      context: ./server
    ports:
      - "4000:${SERVER_PORT}"
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
      - "DB_HOST=chat-app-postgres"
      - "DB_USER=${DB_USER}"
      - "DB_PASS=${DB_PASS}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - chat-app-postgres
      # - chat-app-redis
    networks:
      - frontend
      - backend
  # chat-app-redis:
  #   image: "redis:alpine"
  chat-app-postgres:
    image: postgres:latest
    container_name: chat-app-postgres
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
  chat-app-nginx:
    image: nginx:latest
    container_name: chat-app-nginx
    networks:
      - frontend
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chat-app-api
networks:
  frontend:
    name: frontend
  backend:
    name: backend
