version: 2.1
jobs:
  frontend-build:
    working_directory: ~/chat-app
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "./client/package-lock.json"}}
      - run:
          name: install packages
          command: cd client && npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "./client/package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Build
          command: cd client && npm run build
  frontend-deploy:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Deploy to GCP
          command: |
            echo 'Deploying...'
            echo 'Deployed!'
  frontend-test:
    working_directory: ~/chat-app
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run:
          name: check folder path
          command: |
            ls -a
            pwd
            cd client
            ls -a
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "./client/package-lock.json"}}
      - run:
          name: install packages
          command: cd client && npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "./client/package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: cd client && npm run test
  frontend-complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'
workflows:
  frontend:
    jobs:
      - frontend-test
      - frontend-build:
          requires:
            - frontend-test
          filters:
            branches:
              only: master
      - frontend-approval:
          type: approval
          requires:
            - frontend-build
          filters:
            branches:
              only: master
      - frontend-deploy:
          requires:
            - frontend-approval
          filters:
            branches:
              only: master
      - frontend-complete:
          requires:
          - frontend-deploy
          filters:
            branches:
              only: master
